(()=>{"use strict";
const CLIENT_ID="484275695655-c7dpkepp6mstvhoq631iln7kclgvajpn.apps.googleusercontent.com",SCOPE="https://www.googleapis.com/auth/drive.file",TOKEN_KEY="promptshelf-mobile-google-token",DB_NAME="promptshelf-mobile",STORE="cache",CACHE_KEY="library",DEVICE_ID_KEY="promptshelf-mobile-device-id",TOKEN_SKEW=90000;
let activePromptId=null,busy=false,toastTimer=null;
function openDb(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function cacheGet(){const db=await openDb();return new Promise((res,rej)=>{const tx=db.transaction(STORE,"readonly"),r=tx.objectStore(STORE).get(CACHE_KEY);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)})}
async function cacheSet(v){const db=await openDb();return new Promise((res,rej)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).put(v,CACHE_KEY);tx.oncomplete=res;tx.onerror=()=>rej(tx.error);tx.onabort=()=>rej(tx.error||new Error("Mobile cache write was aborted."))})}
function deviceId(){try{let id=localStorage.getItem(DEVICE_ID_KEY);if(!id){id=crypto.randomUUID();localStorage.setItem(DEVICE_ID_KEY,id)}return id}catch{return`mobile-${Date.now()}`}}
function currentToken(){try{const p=JSON.parse(sessionStorage.getItem(TOKEN_KEY)||"null");return p?.accessToken&&Number(p.expiresAt)>Date.now()+TOKEN_SKEW?p.accessToken:null}catch{return null}}
function saveToken(r){try{sessionStorage.setItem(TOKEN_KEY,JSON.stringify({accessToken:r.access_token,expiresAt:Date.now()+Math.max(60,Number(r.expires_in||3600))*1000}))}catch{}}
function waitGoogle(timeout=8000){if(window.google?.accounts?.oauth2?.initTokenClient)return Promise.resolve(window.google.accounts.oauth2);return new Promise((res,rej)=>{const start=Date.now(),timer=setInterval(()=>{const o=window.google?.accounts?.oauth2;if(o?.initTokenClient){clearInterval(timer);res(o)}else if(Date.now()-start>=timeout){clearInterval(timer);rej(new Error("Google authorization could not load. Check the connection and try again."))}},100)})}
async function token(loginHint){const existing=currentToken();if(existing)return existing;const oauth=await waitGoogle(),client=oauth.initTokenClient({client_id:CLIENT_ID,scope:SCOPE,callback:()=>{}});return new Promise((res,rej)=>{client.callback=r=>{if(r?.error)return rej(new Error(r.error_description||r.error));if(!r?.access_token)return rej(new Error("Google did not return a Drive access token."));saveToken(r);res(r.access_token)};const opts={prompt:""};if(loginHint)opts.login_hint=loginHint;client.requestAccessToken(opts)})}
async function driveFetch(t,url,options={}){const headers=new Headers(options.headers||{});headers.set("Authorization",`Bearer ${t}`);const r=await fetch(url,{...options,headers});if(!r.ok){let detail="";try{detail=(await r.clone().json())?.error?.message||""}catch{}throw new Error(`Google Drive request failed (${r.status})${detail?`: ${detail}`:"."}`)}return r}
async function metadata(t,id){return(await driveFetch(t,`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(id)}?fields=id,name,version,modifiedTime,size,trashed,appProperties`)).json()}
async function documentFromDrive(t,id){const d=await(await driveFetch(t,`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(id)}?alt=media`)).json();if(d?.app!=="PromptShelf"||Number(d?.syncFormatVersion)!==2||!d.library)throw new Error("The PromptShelf Drive file is not a supported Sync Format 2 document. Nothing was changed.");return d}
function canonical(v){if(Array.isArray(v))return`[${v.map(canonical).join(",")}]`;if(v&&typeof v==="object")return`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonical(v[k])}`).join(",")}}`;return JSON.stringify(v)}
function sameLibrary(a,b){return canonical(a)===canonical(b)}
async function upload(t,id,doc){const meta={mimeType:"application/json",appProperties:{promptshelf:"sync-state",syncFormatVersion:"2"}},form=new FormData();form.append("metadata",new Blob([JSON.stringify(meta)],{type:"application/json; charset=UTF-8"}));form.append("file",new Blob([JSON.stringify(doc,null,2)],{type:"application/json; charset=UTF-8"}));return(await driveFetch(t,`https://www.googleapis.com/upload/drive/v3/files/${encodeURIComponent(id)}?uploadType=multipart&fields=id,name,version,modifiedTime,size`,{method:"PATCH",body:form})).json()}
function status(s){const e=document.getElementById("status");if(e)e.textContent=s}
function toast(s,d=3000){const e=document.getElementById("toast");if(!e)return;clearTimeout(toastTimer);e.textContent=s;e.classList.remove("hidden");toastTimer=setTimeout(()=>e.classList.add("hidden"),d)}
function cachedPrompt(c,id){return c?.library?.prompts?.find(p=>String(p.id)===String(id))||null}
async function toggle(id,button){if(busy)return;busy=true;const old=button?.textContent;if(button){button.disabled=true;button.textContent="…"}try{const c=await cacheGet();if(!c?.library||c.source!=="drive")throw new Error("Favorite syncing is available only after loading PromptShelf from Google Drive.");const fileId=c.meta?.fileId;if(!fileId)throw new Error("Tap Refresh before changing a favorite.");status("Checking Google Drive before saving favorite…");const t=await token(c.account?.emailAddress||null),before=await metadata(t,fileId),doc=await documentFromDrive(t,fileId);if(c.meta?.libraryId&&doc.library?.libraryId&&String(c.meta.libraryId)!==String(doc.library.libraryId))throw new Error("The Google Drive PromptShelf library identity changed. Nothing was written. Refresh first.");if(!sameLibrary(c.library,doc.library))throw new Error("PromptShelf changed in Google Drive since this phone last refreshed. Nothing was overwritten. Tap Refresh, then try again.");const afterDownload=await metadata(t,fileId);if(String(afterDownload.version)!==String(before.version))throw new Error("PromptShelf changed while the phone was preparing the save. Nothing was overwritten. Tap Refresh, then try again.");const p=doc.library.prompts.find(x=>String(x.id)===String(id));if(!p)throw new Error("That prompt no longer exists in Google Drive. Refresh first.");const now=new Date().toISOString();p.isFavorite=!Boolean(p.isFavorite);p.updatedAt=now;doc.updatedAt=now;doc.sourceDeviceId=deviceId();const updated=await upload(t,fileId,doc);c.library=structuredClone(doc.library);c.meta={...(c.meta||{}),updatedAt:updated.modifiedTime||now,fileVersion:updated.version||null};c.cachedAt=now;await cacheSet(c);status(`Favorite saved to Google Drive · ${new Date().toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}`);toast(p.isFavorite?"Added to Favorites.":"Removed from Favorites.");setTimeout(()=>location.reload(),650)}catch(e){console.error(e);status(e.message);toast(e.message,5600);if(button){button.disabled=false;button.textContent=old}}finally{busy=false}}
function enhanceCards(){document.querySelectorAll(".card[data-prompt-id]").forEach(card=>{if(card.querySelector(".rc4-card-favorite"))return;const favorite=Boolean(card.querySelector(".star")),b=document.createElement("button");b.type="button";b.className=`rc4-card-favorite${favorite?" is-favorite":""}`;b.textContent=favorite?"★":"☆";b.setAttribute("aria-label",favorite?"Remove from Favorites":"Add to Favorites");b.onclick=e=>{e.preventDefault();e.stopPropagation();toggle(card.dataset.promptId,b)};card.appendChild(b)})}
function ensureDetailButton(){const row=document.querySelector("#promptDialog .copy-row");if(!row||document.getElementById("rc4DetailFavorite"))return;const b=document.createElement("button");b.id="rc4DetailFavorite";b.type="button";b.className="btn rc4-detail-favorite";b.textContent="☆ Favorite";b.onclick=()=>{if(activePromptId)toggle(activePromptId,b)};row.prepend(b)}
async function refreshDetail(){const b=document.getElementById("rc4DetailFavorite");if(!b||!activePromptId)return;try{const c=await cacheGet(),p=cachedPrompt(c,activePromptId),fav=Boolean(p?.isFavorite);b.textContent=fav?"★ Favorited":"☆ Favorite";b.classList.toggle("is-favorite",fav)}catch{}}
function labels(){const v=document.querySelector(".brand-copy span");if(v)v.textContent="Mobile Library · v0.19 RC4";const settings=document.querySelector("#settingsDialog .sheet-head span");if(settings)settings.textContent="RC4 · Favorites sync"}
function init(){labels();ensureDetailButton();enhanceCards();document.addEventListener("click",e=>{const card=e.target.closest?.(".card[data-prompt-id]");if(card&&!e.target.closest?.(".rc4-card-favorite")){activePromptId=card.dataset.promptId;setTimeout(refreshDetail,0)}},true);new MutationObserver(()=>{enhanceCards();ensureDetailButton();if(document.getElementById("promptDialog")?.open)refreshDetail()}).observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:["open"]})}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();
})();
